export const GET_OPERATIONS = "GET_OPERATIONS";
export const CREATE_OPERATION = "CREATE_OPERATION";
export const MODIFY_OPERATION = "MODIFY_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";